/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAvatarStudioSignRouteImport } from './routes/api/public/avatar-studio-sign'
import { Route as ApiPublicAvatarStudioSplatRouteImport } from './routes/api/public/avatar-studio/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarStudioSignRoute =
  ApiPublicAvatarStudioSignRouteImport.update({
    id: '/api/public/avatar-studio-sign',
    path: '/api/public/avatar-studio-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAvatarStudioSplatRoute =
  ApiPublicAvatarStudioSplatRouteImport.update({
    id: '/api/public/avatar-studio/$',
    path: '/api/public/avatar-studio/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/avatar-studio-sign': typeof ApiPublicAvatarStudioSignRoute
  '/api/public/avatar-studio/$': typeof ApiPublicAvatarStudioSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/avatar-studio-sign': typeof ApiPublicAvatarStudioSignRoute
  '/api/public/avatar-studio/$': typeof ApiPublicAvatarStudioSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/avatar-studio-sign': typeof ApiPublicAvatarStudioSignRoute
  '/api/public/avatar-studio/$': typeof ApiPublicAvatarStudioSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/avatar-studio-sign'
    | '/api/public/avatar-studio/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/avatar-studio-sign' | '/api/public/avatar-studio/$'
  id:
    | '__root__'
    | '/'
    | '/api/public/avatar-studio-sign'
    | '/api/public/avatar-studio/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAvatarStudioSignRoute: typeof ApiPublicAvatarStudioSignRoute
  ApiPublicAvatarStudioSplatRoute: typeof ApiPublicAvatarStudioSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar-studio-sign': {
      id: '/api/public/avatar-studio-sign'
      path: '/api/public/avatar-studio-sign'
      fullPath: '/api/public/avatar-studio-sign'
      preLoaderRoute: typeof ApiPublicAvatarStudioSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar-studio/$': {
      id: '/api/public/avatar-studio/$'
      path: '/api/public/avatar-studio/$'
      fullPath: '/api/public/avatar-studio/$'
      preLoaderRoute: typeof ApiPublicAvatarStudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAvatarStudioSignRoute: ApiPublicAvatarStudioSignRoute,
  ApiPublicAvatarStudioSplatRoute: ApiPublicAvatarStudioSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
